### PR TITLE
Support multiple load balancing listeners per container

### PR DESCRIPTION
**Pull request by thebengeu**
Fixes pulumi/pulumi-aws#1258.

### CODE REVIEW

**Comment by leezen** [comment]
Thanks for taking a look and making a fix.

**Comment by mikehroth** [comment]
Would love to see this get deployed – what is the timeline?

**Comment by profsmallpine** [comment]
@leezen ping, can we get a release for this? Thanks!

**Comment by leezen** [comment]
Sorry, not sure how I missed the first ping. I'll get a PR drafted to cut a release right now.

**Pull request merged**
