### PR TITLE
Allow nullable logGroup, taskRole, and executionRole for TaskDefinitionArgs, EC2TaskDefinitionArgs, and FargateTaskDefinitionArgs

### LINKED ISSUE #514: [ecs.TaskDefinition] Type 'null' is not assignable to type 'LogGroup'
Hi. On creating TaskDefinition, I want no `logGroup` to be created since I use Datadog logs to collect ECS container logs.

Following your instruction, I have to set `logGroup` null.
https://github.com/pulumi/pulumi-awsx/blob/a7bb7917685e2eec8ab48db0e5213cf38e88c465/nodejs/awsx/ecs/ec2Service.ts#L145-L155

I configured like this:
```index.ts
return new awsx.ecs.EC2TaskDefinition(`my-task-def`,{
      family: `my-task-def`,
      containers: {
        api: apiContainer,
      },
      taskRole: taskRole,
      executionRole: taskExecutionRole,
      logGroup: null,
    });
```

Then I got this:
```
Type 'null' is not assignable to type 'LogGroup | undefined'
```

probably `logGroup`'s type annotation should be like this:
```ec2Service.ts
 logGroup?: aws.cloudwatch.LogGroup|null;
```

The same goes for `taskRole` field.

### PR DESCRIPTION
**Pull request by leezen**
Fixes #514

### CODE REVIEW

**Comment by yuichiro12** [comment]
Thank you, @leezen.
Seeing the code comment in TaskDefinitionArgs, `taskRole` should also be nullable.
https://github.com/pulumi/pulumi-awsx/blob/a7bb7917685e2eec8ab48db0e5213cf38e88c465/nodejs/awsx/ecs/ec2Service.ts#L151-L155

**Comment by leezen** [comment]
Thanks for pointing that out. I'll include that as part of this change as well.

**Comment by yuichiro12** [comment]
Thank you. `FargateTaskDefinitionArgs ` also has same fields.
https://github.com/pulumi/pulumi-awsx/blob/a7bb7917685e2eec8ab48db0e5213cf38e88c465/nodejs/awsx/ecs/fargateService.ts#L278-L288

**Comment by leezen** [comment]
Of course! Thanks for catching that.

**Comment by ypresto** [comment]
I have already sent a PR... :joy: #502

**Comment by leezen** [comment]
Ahhh! Sorry, not sure how I missed that.

**Comment by ypresto** [comment]
Anyway thanks for fixing it! :pray:

**Pull request merged**
