### PR TITLE
Correctly support apiKeySource in classic provider

### PR DESCRIPTION
**Pull request by lukehoban**
We were previously passing apiKeySource only via Swagger.  Even though AWS API Gateway does include the API key source in the swagger on output, it apparently does not read it from the swagger on updates.

However, it does support passing it outside of the Swagger, so we just pass this along directly to the RestAPI constructor is specified.

We could in principle *stop* sending it in the Swagger as well (since I don't think it's read from there at all), but I am avoiding changing that in case it has other subtle impacts on behaviour.

Fixes https://github.com/pulumi/pulumi-awsx/issues/1057.

### CODE REVIEW

**Comment by thomas11** [comment]
Thank you @lukehoban! Your PR description doesn't say, so I gotta ask, did you test this change manually?

It would be awesome to have a two-step test in `examples/` that repros the issue submitter's issue with editing the `apiKeySource` after `up` but the effort might not be warranted for an uncommon issue in awsx-classic.

**Comment by lukehoban** [comment]
> It would be awesome to have a two-step test in examples/ that repros the issue submitter's issue with editing the apiKeySource after up but the effort might not be warranted for an uncommon issue in awsx-classic.

Agreed - I'll get a test added before we merge this.

**Comment by lukehoban** [comment]
@thomas11 Test added - ready for review.

**Review by mjeffryes — APPROVED** [review]
Thanks, Luke! I've filed an issue for us to port this fix into pulumi-aws-apigateway as well

**Comment by lukehoban** [comment]
> I've filed an issue for us to port this fix into pulumi-aws-apigateway as well

Great. I’ve got a PR nearly ready for that - so happy to finish that up once this is merged.

**Review by thomas11 — APPROVED** [review]

**Comment by lukehoban** [comment]
> I’ve got a PR nearly ready for that - so happy to finish that up once this is merged.

Tracked in https://github.com/pulumi/pulumi-aws-apigateway/pull/112.

**Pull request merged**
