### PR TITLE
Create an explicit RestApiPolicy if a policy is specified

### PR DESCRIPTION
**Pull request by leezen**
Fixes https://github.com/pulumi/pulumi-awsx/issues/627

### CODE REVIEW

**Review by stack72 — APPROVED** [review]

**Comment by cabeaulac** [comment]
This is great! Thanks!

**Comment by cabeaulac** [comment]
The code looks good. However, I just tested it. I had to run "pulumi up" twice still. Can you all test it on your side please? 
I'm not specifying the policy separate anymore, but having to run the pipeline twice is still not good.
Snippet.
`let endpoint = new awsx.apigateway.API(`my-private-api-${stackEnv}`, {

    restApiArgs: {
        endpointConfiguration: {
            types: "PRIVATE",
            vpcEndpointIds: [execApiVpcEndpointId],
        },
        policy: executeApiPolicy,
    },
`

**Comment by leezen** [comment]
@cabeaulac Could you verify that you're running against the dev build of this package? I would expect in a preview for there to be a `RestApiPolicy` resource created.

**Comment by cabeaulac** [comment]
I'm running pulumi v2.18.2
Is this fix not released yet?

**Comment by stack72** [comment]
Hi @cabeaulac 

it is not - it's in the dev version of pulumi-awsx not pulumi itself

P.

**Comment by cabeaulac** [comment]
Hi @stack72 
Next silly question. How will I know when it's released since #627 is closed already?
Thanks!

**Comment by stack72** [comment]
Hey @cabeaulac 

So, we will be releasing pulumi-awsx 0.24.0 this week - you can keep an eye on the CHANGELOG or the releases to show when it's released

P.

**Comment by cabeaulac** [comment]
Thanks @stack72 !

**Pull request merged**
