### PR TITLE
Upgrade aws to 6.9.0

### PR DESCRIPTION
**Pull request by VenelinMartinov**
Should address https://github.com/pulumi/pulumi-awsx/issues/1156

### CODE REVIEW

**Review by iwahbe — APPROVED** [review]
This looks good to me. @thomas11 Can you take a look?

**Review by thomas11 — COMMENTED** [review]
https://github.com/pulumi/pulumi-awsx/blob/master/schemagen/pkg/gen/schema.go has the version range specs for all languages for the SDKs. For Python and C#, they're just 6.*. If you think we need v6.9, those should be edited as well. `dependencies.Aws` gives you access to the version defined in `awsx/package.json`.

**Comment by VenelinMartinov** [comment]
Seems unlikely that the SDK should require the new version when there were no changes in awsx for this upgrade.

How can I make sure that the sdks work with the old one?

**Comment by mnlumi** [comment]
Is there any harm to ensuring all SDKs are at a minimum of 6.9.0? Would be good to be consistent to ensure we have this tags issue resolved across the board.

**Comment by VenelinMartinov** [comment]
I believe the tags issue should be fixed by upgrading the AWS provider. https://github.com/pulumi/pulumi-aws/pull/2944/files has no sdk changes. I don't think upgrading the SDKs should be required and it would force users to upgrade the sdks too.

Do we generally do that?

**Comment by thomas11** [comment]
> I believe the tags issue should be fixed by upgrading the AWS provider. https://github.com/pulumi/pulumi-aws/pull/2944/files has no sdk changes. I don't think upgrading the SDKs should be required and it would force users to upgrade the sdks too.
> 
> Do we generally do that?

No. The Python and C# dependencies are at the minimum of v6.

For this change I don't think it's needed. It is a bit odd that we're inconsistent between languages. Although some, like Go, don't support ranges at all.

**Pull request merged**
