### PR TITLE
Update classic vpc nat gateway to use `domain: "vpc"` instead of deprecated `vpc: true`

### PR DESCRIPTION
**Pull request by eigilsagafos**

### CODE REVIEW

**Comment by t0yv0** [comment]
This looks good, thank you @eigilsagafos ! It seems to address a deprecation. Let me try to run tests here.

**Comment by eigilsagafos** [comment]
@t0yv0 I updated based on the failing lint test. Could you trigger the tests again?

**Comment by t0yv0** [comment]
Let's try it. Thank you!

**Review by t0yv0 — APPROVED** [review]

**Pull request merged**
