### PR TITLE
Adopt IPAM functionality

### PR DESCRIPTION
**Pull request by BongoEADGC6**
In reference to Issue: https://github.com/pulumi/pulumi-awsx/issues/872

### CODE REVIEW

**Comment by rquitales** [comment]
@BongoEADGC6 Thanks for submitting this PR. Overall, this looks good to me, but we have a test failing as the code you submitted is not linted. Could you run `make lint lint_classic` and commit the changes?
Thanks!

**Review by rquitales — CHANGES_REQUESTED** [review]
@BongoEADGC6 Thanks for submitting this PR. Overall, this looks good to me, but we have a test failing as the code you submitted is not linted. Could you run make lint lint_classic and commit the changes?
Thanks!

**Comment by BongoEADGC6** [comment]
@rquitales Done and ready for approval

**Review by rquitales — APPROVED** [review]
Thanks for submitting this fix, and sorry for getting this merged in late.

**Pull request merged**
