### PR TITLE
fix: add necessary dependencies for type checking to succeed

### LINKED ISSUE #853: Node package has a transitive dependency on `awsx-lambda` not in schema.json
It looks like the package `aws-lambda` and its types are a dependency of `@pulumi/awsx`. On this repo: https://github.com/AaronFriel/awsx-fargate-deps

Type checking fails with:


```
❯ yarn tsc --noEmit
yarn run v1.22.17
warning package.json: No license field
$ /home/friel/go/src/github.com/pulumi/pulumi-yaml/pkg/tests/transpiled_examples/awsx-fargate/nodejs/node_modules/.bin/tsc --noE
mit
node_modules/@pulumi/awsx/classic/apigateway/api.d.ts:3:28 - error TS2307: Cannot find module 'aws-lambda'.

3 import * as awslambda from "aws-lambda";
                             ~~~~~~~~~~~~

node_modules/@pulumi/awsx/classic/apigateway/lambdaAuthorizer.d.ts:3:28 - error TS2307: Cannot find module 'aws-lambda'.

3 import * as awslambda from "aws-lambda";
                             ~~~~~~~~~~~~

node_modules/@pulumi/awsx/classic/ec2/vpcTopology.d.ts:3:174 - error TS2304: Cannot find name 'AvailabilityZoneDescription'.

3 export declare function create(resource: pulumi.Resource | undefined, vpcName: string, vpcCidr: string, ipv6CidrBlock: pulumi.
Output<string> | undefined, availabilityZones: AvailabilityZoneDescription[], numberOfNatGateways: number, assignGeneratedIpv6Ci
drBlock: pulumi.Input<boolean>, subnetArgsArray: VpcSubnetArgs[]): VpcTopologyDescription;
                                                                                                                                
                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@pulumi/awsx/classic/ec2/vpcTopology.d.ts:3:322 - error TS2304: Cannot find name 'VpcTopologyDescription'.

3 export declare function create(resource: pulumi.Resource | undefined, vpcName: string, vpcCidr: string, ipv6CidrBlock: pulumi.
Output<string> | undefined, availabilityZones: AvailabilityZoneDescription[], numberOfNatGateways: number, assignGeneratedIpv6Ci
drBlock: pulumi.Input<boolean>, subnetArgsArray: VpcSubnetArgs[]): VpcTopologyDescription;
                                                                                                                                
                                                                                                                                
                                                                   ~~~~~~~~~~~~~~~~~~~~~~


Found 4 errors.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Running `yarn add aws-lambda @types/aws-lambda` - both were needed - satisfies TypeScript, so I think we need to add those dependencies for types to check properly.

https://github.com/pulumi/pulumi-awsx/blob/5fbb62b83848d9c837446ddc9bd3386b4ca6a6e0/schemagen/pkg/gen/schema.go#L67-L80

### PR DESCRIPTION
**Pull request by AaronFriel**
Moves two dependencies out of devDeps into primary deps, and removes internal annotations that caused type errors.

Fixes #853

### CODE REVIEW

**Comment by danielrbradley** [comment]
Interestingly, we don't actually reference any executable code from this import - it's only there for the types. If we were to upgrade to Typescript 3.8 (released Feb 2020) or later then we could just change the import to:

```typescript
import type * as awslambda from "aws-lambda";
       ^
```

**Comment by AaronFriel** [comment]
@danielrbradley I think we still @types/aws-lambda in the dependencies block, otherwise downstream consumers don't get the types and Typescript fails to resolve them.

**Review by danielrbradley — APPROVED** [review]
Ok, that sounds good, merge at will.

**Comment by AaronFriel** [comment]
ty @danielrbradley!

**Pull request merged**
