### PR TITLE
Create CapacityProviderService to make it possible to use capacity provider strategies

### LINKED ISSUE #599: FargateService cannot specify both launchType and capacityProviderStrategies
The `launchType` is currently [explicitly set to `FARGATE`](https://github.com/pulumi/pulumi-awsx/blob/f4a7719f6354e9933be3c63de105c5a8b641462b/nodejs/awsx/ecs/fargateService.ts#L220). When using `capacityProviderStrategies`, you cannot also specify a `launchType`. If you try to, `pulumi up` will fail with this error. 

```
InvalidParameterException: Specifying both a launch type and capacity provider strategy is not supported. Remove one and try again.
```

Here is a minimal repro. 

```typescript
import * as awsx from "@pulumi/awsx";

new awsx.ecs.Cluster("cluster", {
    capacityProviders: ["FARGATE", "FARGATE_SPOT"],
    defaultCapacityProviderStrategies: [{
        base: 0,
        capacityProvider: "FARGATE",
        weight: 0
    }, {
        base: 0,
        capacityProvider: "FARGATE_SPOT",
        weight: 1
    }],
})

new awsx.ecs.FargateService("service", {
    desiredCount: 1,
    taskDefinitionArgs: {
        containers: {
            nginx: {
                image: "nginx:latest",
                memory: 512
            }
        }
    },
    capacityProviderStrategies: [{
        capacityProvider: "FARGATE_SPOT",
        weight: 1
    }]
})
```

Explicitly specifying the `launchType` also prevents the cluster default `capacityProviderStrategy` from being applied. 

From the [RunTask API doc on capacityProviderStrategy](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RunTask.html#API_RunTask_RequestParameters): 
> If a `capacityProviderStrategy` is specified, the `launchType` parameter must be omitted. If no `capacityProviderStrategy` or `launchType` is specified, the `defaultCapacityProviderStrategy` for the cluster is used.

To fix this, I suggest allowing the `launchType` parameter to be passed in to the `FargateService`.

### PR DESCRIPTION
**Pull request by danieldspx**
From #599 I  modified @leezen  class name a bit and called it `CapacityProviderService` and you pass the taskDefinition that would either be a FargateTaskDefinition or EC2TaskDefinition. With that, the user would know exactly wich path he is going. Now underlying capacity provider can be anything and we can still leverage the cluster default capacity provider strategy without any extra flag.

Note that I've implemented a different idea before (#643) but as @leezen said, It makes more sense to have a different class for this. Also, from now on you can't define `capacityProviderStrategies` in `FargateService` nor `EC2Service`. In that way, this PR fixes #599.

### CODE REVIEW

**Review by leezen — COMMENTED** [review]
Thanks for doing this! Overall, looks good. If you could please add a test or two (see `nodejs/awsx/aws_test.go` for how this works), that'd be great so we can make sure this is working properly. I also added a comment about keeping `getSubnets` internal to the module.

**Comment by danieldspx** [comment]
@leezen I guess that for EC2 capacity provider startegies I should create an autoscaling group, and with that create a capacity provider in the cluster and then use it in the CapacityProviderService . But I could not come up with a test easyli for this. I am more used with Fargate. Could you help me? I could not find any pulumi example for autoscaling group usage.

**Comment by leezen** [comment]
https://www.pulumi.com/docs/guides/crosswalk/aws/ecs/#creating-an-auto-scaling-group-for-ecs-cluster-instances has an example of doing this

**Comment by danieldspx** [comment]
The tests failed so I tryed to `pulumi up` the same code from test and I got the same error message. And I discovered that I had not passed the `launchType` on service creation. This would lead the default launch type to be used ("EC2") and we know that `assignPublicIp = true` (which is true for Fargate in this example) would cause that error message. Now that is fixed.

**Comment by danieldspx** [comment]
The problem was the the ecs.Service was setting `EC2` as the launch type if `args.launchType` was undefined. I've tested both and they work fine.

For the EC2 I got an `service (service-name) was unable to place a task because no container instance met all of its requirements. Reason: No Container Instances were found in your capacity provider.` and the reason is clear, but I did not want to creat any instances to avoid costs. I think both tests now should pass :smile:

**Comment by danieldspx** [comment]
Error now was with the custom strategy: `'One or more security groups in the launch configuration are not linked to the VPCs configured in the Auto Scaling group`. I am not so sure if the change I've made will fix the problem.

There is still the option to pass the Cluster's security groups to the launch configuration args. If you think I should do it, just tell me.
```ts
...
const asg = cluster.createAutoScalingGroup("asg", {
  ...
  launchConfigurationArgs: { instanceType: "t2.micro", securityGroups: cluster.securityGroups },
}, providerOpts);
...

**Comment by leezen** [comment]
`createAutoscalingGroups` defaults to passing in the cluster's groups (https://github.com/pulumi/pulumi-awsx/blob/ea0c2f3afd95dcf47c5bac187843e7b66418ff9d/nodejs/awsx/ecs/cluster.ts#L85), so I don't think that's the issue? I dug a little bit into this, but nothing stands out. I'll try to spend more time tomorrow or Monday or if you are able to try taking a look, that'd be appreciated.

**Comment by leezen** [comment]
Oh wait, I see... you have a commit since the test ran to pass in the default VPC to the cluster. Yes, that should make the difference because in the previous ordering the cluster will create its own VPC, which is different from the default. Let me try re-running the tests.

**Comment by leezen** [comment]
To make this work, I think we need to unwind some dependencies around the `CapacityProvider` which has to exist before the `Cluster` (because there's no way to modify the cluster w/ the `CapacityProvider` after the fact in a single shot program). But, the `CapacityProvider` requires the `AutoScalingGroup` to exist, which in turns relies on having the `Cluster` identifier so that the boot parameters can correctly register instances. Similarly, the ASG relies on sharing a security group with the `Cluster`.

In order to unwind these dependencies, we can set the cluster identifier and security groups upfront, which results in the following:

```typescript
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";
import * as pulumi from "@pulumi/pulumi";
import * as random from "@pulumi/random";

const config = new pulumi.Config("aws");
const providerOpts = { provider: new aws.Provider("prov", { region: <aws.Region>config.require("envRegion") }) };

const vpc = awsx.ec2.Vpc.getDefault(providerOpts);

const clusterName = "cluster";
const clusterIdentifier = new random.RandomString("cluster", {
  special: false,
  upper: false,
  length: 6,
}).result.apply(s => "cluster-" + s);

// Create the cluster's security group ahead of time so we can use it for the ASG.
const clusterSecurityGroup = awsx.ecs.Cluster.createDefaultSecurityGroup(clusterName, vpc, providerOpts);

const userData: awsx.autoscaling.AutoScalingUserData = {
  extraBootcmdLines: () => clusterIdentifier.apply(clusterId =>
    [{ contents: `- echo ECS_CLUSTER='${clusterId}' >> /etc/ecs/ecs.config` }]),
};

const asg = new awsx.autoscaling.AutoScalingGroup("asg", {
  vpc,
  subnetIds: vpc.publicSubnetIds,
  templateParameters: { minSize: 1 },
  launchConfigurationArgs: {
    instanceType: "t2.micro",
    securityGroups: [clusterSecurityGroup],
    userData,
  },
}, providerOpts);

const cp = new aws.ecs.CapacityProvider("capacity-provider", {
  autoScalingGroupProvider: {
    autoScalingGroupArn: asg.group.arn,
  },
}, providerOpts);

const cluster = new awsx.ecs.Cluster(clusterName, {
  name: clusterIdentifier,
  vpc,
  capacityProviders: [ cp.name ],
  securityGroups: [clusterSecurityGroup],
}, providerOpts);
```

I've swapped this in for the relevant parts of what's currently committed to this PR, tested it, and it works.

**Comment by danieldspx** [comment]
> To make this work, I think we need to unwind some dependencies around the `CapacityProvider` which has to exist before the `Cluster` (because there's no way to modify the cluster w/ the `CapacityProvider` after the fact in a single shot program). But, the `CapacityProvider` requires the `AutoScalingGroup` to exist, which in turns relies on having the `Cluster` identifier so that the boot parameters can correctly register instances. Similarly, the ASG relies on sharing a security group with the `Cluster`.
> 
> In order to unwind these dependencies, we can set the cluster identifier and security groups upfront, which results in the following:
> 
> ```ts
> import * as aws from "@pulumi/aws";
> import * as awsx from "@pulumi/awsx";
> import * as pulumi from "@pulumi/pulumi";
> import * as random from "@pulumi/random";
> 
> const config = new pulumi.Config("aws");
> const providerOpts = { provider: new aws.Provider("prov", { region: <aws.Region>config.require("envRegion") }) };
> 
> const vpc = awsx.ec2.Vpc.getDefault(providerOpts);
> 
> const clusterName = "cluster";
> const clusterIdentifier = new random.RandomString("cluster", {
>   special: false,
>   upper: false,
>   length: 6,
> }).result.apply(s => "cluster-" + s);
> 
> // Create the cluster's security group ahead of time so we can use it for the ASG.
> const clusterSecurityGroup = awsx.ecs.Cluster.createDefaultSecurityGroup(clusterName, vpc, providerOpts);
> 
> const userData: awsx.autoscaling.AutoScalingUserData = {
>   extraBootcmdLines: () => clusterIdentifier.apply(clusterId =>
>     [{ contents: `- echo ECS_CLUSTER='${clusterId}' >> /etc/ecs/ecs.config` }]),
> };
> 
> const asg = new awsx.autoscaling.AutoScalingGroup("asg", {
>   vpc,
>   subnetIds: vpc.publicSubnetIds,
>   templateParameters: { minSize: 1 },
>   launchConfigurationArgs: {
>     instanceType: "t2.micro",
>     securityGroups: [clusterSecurityGroup],
>     userData,
>   },
> }, providerOpts);
> 
> const cp = new aws.ecs.CapacityProvider("capacity-provider", {
>   autoScalingGroupProvider: {
>     autoScalingGroupArn: asg.group.arn,
>   },
> }, providerOpts);
> 
> const cluster = new awsx.ecs.Cluster(clusterName, {
>   name: clusterIdentifier,
>   vpc,
>   capacityProviders: [ cp.name ],
>   securityGroups: [clusterSecurityGroup],
> }, providerOpts);
> ```
> 
> I've swapped this in for the relevant parts of what's currently committed to this PR, tested it, and it works.

Awesome work. I did the changes you suggested and hope this finally works :pray:

**Comment by bbstilson** [comment]
I can't seem to find any documentation of this feature. The only reason I stumbled across it is because my IDE autocompleted. Is there a reason the [awsx/ecs](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/awsx/ecs/) module documentation hasn't been updated? Cheers

**Comment by danieldspx** [comment]
> I can't seem to find any documentation of this feature. The only reason I stumbled across it is because my IDE autocompleted. Is there a reason the [awsx/ecs](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/awsx/ecs/) module documentation hasn't been updated? Cheers

Also could not find it. If I remember correctly it was on the docs before and now it is gone. Do you have any idea why @leezen ?

@bbstilson  if you really want to know a bit more about it you can refer to [this article](https://medium.com/@danieldspx/how-to-set-up-your-aws-ecs-cluster-using-pulumi-2340041dc197) I wrote (specifically in the point 4 of the article).

**Comment by leezen** [comment]
Unfortunately, I'm not sure this was actually ever correctly updated (see commit history for https://github.com/pulumi/docs/tree/master/content/docs/reference/pkg/nodejs/pulumi/awsx -- it seems the last time we released, the workflow for updating the docs didn't complete correctly -- https://github.com/pulumi/docs/runs/3750842256?check_suite_focus=true).

**Comment by leezen** [comment]
I've opened https://github.com/pulumi/docs/pull/7077 to correct this

**Comment by bbstilson** [comment]
Thanks for the prompt response @leezen  and @danieldspx ! I appreciate it.

**Pull request merged**
